### ISSUE TITLE
Url to display in superstyler.php

### ISSUE THREAD

**Issue by Alienpruts** [kewljuice/be.ctrl.superstyler#3]
This code is currently beeing used to display the path to the module in the overview (settings) page. 

``` php
$url = CRM_Utils_System::url() . 'civicrm/ctrl/superstyler';
```

However : the url() method is generally used to display an internal path (even if it is outside of CIviCRM). It might be better to use the baseURL() method instead.

``` php
$url = CRM_Utils_System::baseURL() . 'civicrm/ctrl/superstyler';
```

This will display the entire path (from the root of the server), instead of just the root of the application. This is not only cosmetical, there can be a very small amount of overhead (url() has 8 lines, baseURL() only 2 lines). 

If needed, the url returned from baseURL() can be cleaned with one line of code to show everything after the server name, still making this a better choice (3 lines total vs 8 lines from the ur() method).

Something worth considering?

**Comment by kewljuice** [comment]
Changed ::url() to baseURL::().

**Comment by Alienpruts** [comment]
Still working yes? :)

**Comment by kewljuice** [comment]
Yes! tnx!
